name: DevSecOps CI Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout (Получаем код)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Обязательно для SonarCloud

      # 2. Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

     # 3. SAST (SonarCloud)
      - name: SAST - SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # ДОБАВИТЬ: -e -X
        run: cd codes/unisystem2023 && mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -e -X
        
     # 4. Установка Snyk CLI
          # Используем готовый Action для установки Snyk CLI
          - name: Install Snyk CLI
            uses: snyk/actions/setup-snyk@v1
            
          # 5. SCA (Snyk Test) - Запускаем в окружении с установленной Java
          - name: SCA - Snyk Test (Зависимости)
            env:
              SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              # Передайте SNYK_TOKEN
            run: |
              # Используем команду run, а не uses:action, чтобы остаться в текущем контейнере
              # Обратите внимание: нужно указать файл pom.xml, как в вашем логе:
              snyk test --maven-aggregate --file=codes/unisystem2023/pom.xml
              # Или, если pom.xml находится в корне: snyk test --maven-aggregate
