name: DevSecOps CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout код
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # обязательно для SonarCloud

      # 2. Setup Java JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Проверка Java (для отладки)
      - name: Check Java
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      # 4. SAST - SonarCloud Scan
      - name: SAST - SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd codes/unisystem2023
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar


      # 5. SCA - Snyk Test (Maven)
      - name: SCA - Snyk Test (Dependencies)
        run: |
            export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
            echo "JAVA_HOME=$JAVA_HOME"
            npm install -g snyk
            mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="codes/unisystem2023/pom.xml"
            snyk test --file=codes/unisystem2023/pom.xml
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


