name: DevSecOps CI Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout (Получаем код)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Обязательно для SonarCloud

      # 2. Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. SAST (SonarCloud)
      - name: SAST - SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # Переходим в папку с pom.xml и запускаем упрощенный анализ
        run: cd codes/unisystem2023 && mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

      # 4. SCA (Snyk)
      - name: SCA - Snyk Test (Зависимости)
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          # Указываем точный путь к pom.xml
          args: --file=codes/unisystem2023/pom.xml
